"use strict";var E=Object.defineProperty;var r=(e,t)=>E(e,"name",{value:t,configurable:!0});var c=(e,t)=>()=>(t||e((t={exports:{}}).exports,t),t.exports);var f=c((R,d)=>{var l={},k=r(e=>{l.lodash=e.require("lodash"),l.async=e.require("async")},"setDependencies");d.exports={setDependencies:k,dependencies:l}});var g=c((W,b)=>{b.exports={name:"TripleStore",version:"0.0.3",author:"hackolade",engines:{hackolade:"7.4.0",hackoladePlugin:"1.2.0"},contributes:{target:{applicationTarget:"TripleStore",title:"TripleStore",versions:["any"]},features:{jaySchemaHasRequiredPatternField:!1,nestedCollections:{isVirtual:!0,hasMultipleParents:!0},graphDB:!0,relationships:{connectOnEntityLevel:!0,hasData:!0},enableForwardEngineering:{jsonDocument:!0,jsonSchema:!0,excel:!0,plugin:!0},enableReverseEngineering:{jsonDocument:!0,jsonSchema:!0,ddl:!0,xsd:!0,excel:!0,plugin:!0},FEScriptCommentsSupported:!0}},description:"Hackolade plugin for Semantic Knowledge Graph TripleStores",disabled:!1,"lint-staged":{"*.{js,json}":"prettier --write"},"simple-git-hooks":{"pre-commit":"npx lint-staged","pre-push":"npx eslint ."},scripts:{lint:"eslint . --max-warnings=0",package:"node esbuild.package.js"},devDependencies:{"@hackolade/hck-esbuild-plugins-pack":"0.0.1",esbuild:"0.21.2","esbuild-plugin-clean":"1.0.1",eslint:"9.2.0","eslint-config-prettier":"9.1.0","eslint-plugin-prettier":"5.1.3","lint-staged":"14.0.1",prettier:"3.2.5","simple-git-hooks":"2.11.1"}}});var h=c((M,y)=>{var o=require("os"),C=require("net"),T=g(),I=r((e,t,s=5e3)=>new Promise((n,i)=>{let u=setTimeout(()=>{p.end(),i(new Error("Connection takes more than 5000 ms"))},s),p=C.createConnection(t||7687,e,()=>{p.end(),clearTimeout(u),n()});p.on("error",D=>{clearTimeout(u),i(D)})}),"checkConnection"),v=r(()=>T.version,"getPluginVersion"),q=r(e=>`Date: ${new Date}
Application version: ${e}
Plugin version: ${v()}

System information:
 Hostname:  ${o.hostname()}
 Platform:  ${o.platform()} ${o.arch()}
 Release:   ${o.release()}
 Uptime:    ${j(o.uptime())}
 Total RAM: ${(o.totalmem()/1073741824).toFixed(2)} GB
 CPU Model: ${o.cpus()[0].model}
 CPU Clock: ${$(o.cpus())} MHZ
 CPU Cores: ${o.cpus().length} cores

`,"getSystemInfo"),$=r(e=>e.reduce((t,s)=>Math.max(t,s.speed),0),"maxClock"),P=r(e=>e<10?"0"+e:e,"prefixZero"),j=r(e=>Math.floor(e/3600)+":"+P(parseInt((e/3600-Math.floor(e/3600))*60)),"toTime"),w={getSystemInfo:q,checkConnection:I};y.exports=w});var{dependencies:m,setDependencies:O}=f(),a="../snippets/",U=h(),A,F,z={"Cartesian 3D":require(a+"cartesian-3d.json"),Cartesian:require(a+"cartesian.json"),"WGS-84-3D":require(a+"point-wgs-84-3d.json"),"WGS-84":require(a+"point-wgs-84.json")};module.exports={connect:r(function(e,t,s,n){S(n)},"connect"),disconnect:r(function(e,t){t()},"disconnect"),testConnection:r(function(e,t,s,n){G("Test connection",e,t),S(n),this.connect(e,t,i=>{this.disconnect(e,()=>{}),s(i)},n)},"testConnection"),getDatabases:r(function(e,t,s){s()},"getDatabases"),getDocumentKinds:r(function(e,t,s){s()},"getDocumentKinds"),getDbCollectionsNames:r(async function(e,t,s,n){s()},"getDbCollectionsNames"),getDbCollectionsData:r(async function(e,t,s,n){s()},"getDbCollectionsData"),getDbCollectionsDataWrapped:r(async function(e,t,s,n){s()},"getDbCollectionsDataWrapped")};var S=r(e=>{O(e),A=m.lodash,F=m.async},"initDependencies");var G=r((e,t,s)=>{s.clear(),s.log("info",U.getSystemInfo(t.appVersion),e),s.log("info",t,"connectionInfo",t.hiddenKeys)},"logInfo");
